// Generated by view binder compiler. Do not edit!
package com.project.sparkwomen.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.button.MaterialButton;
import com.project.sparkwomen.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final LinearLayout fifth;

  @NonNull
  public final LinearLayout first;

  @NonNull
  public final LinearLayout fourth;

  @NonNull
  public final ImageView logout;

  @NonNull
  public final MaterialButton panicBtn;

  @NonNull
  public final RelativeLayout relativeLayout;

  @NonNull
  public final LinearLayout second;

  @NonNull
  public final LinearLayout third;

  @NonNull
  public final View topleftoval;

  private ActivityMainBinding(@NonNull RelativeLayout rootView, @NonNull LinearLayout fifth,
      @NonNull LinearLayout first, @NonNull LinearLayout fourth, @NonNull ImageView logout,
      @NonNull MaterialButton panicBtn, @NonNull RelativeLayout relativeLayout,
      @NonNull LinearLayout second, @NonNull LinearLayout third, @NonNull View topleftoval) {
    this.rootView = rootView;
    this.fifth = fifth;
    this.first = first;
    this.fourth = fourth;
    this.logout = logout;
    this.panicBtn = panicBtn;
    this.relativeLayout = relativeLayout;
    this.second = second;
    this.third = third;
    this.topleftoval = topleftoval;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.fifth;
      LinearLayout fifth = ViewBindings.findChildViewById(rootView, id);
      if (fifth == null) {
        break missingId;
      }

      id = R.id.first;
      LinearLayout first = ViewBindings.findChildViewById(rootView, id);
      if (first == null) {
        break missingId;
      }

      id = R.id.fourth;
      LinearLayout fourth = ViewBindings.findChildViewById(rootView, id);
      if (fourth == null) {
        break missingId;
      }

      id = R.id.logout;
      ImageView logout = ViewBindings.findChildViewById(rootView, id);
      if (logout == null) {
        break missingId;
      }

      id = R.id.panicBtn;
      MaterialButton panicBtn = ViewBindings.findChildViewById(rootView, id);
      if (panicBtn == null) {
        break missingId;
      }

      id = R.id.relativeLayout;
      RelativeLayout relativeLayout = ViewBindings.findChildViewById(rootView, id);
      if (relativeLayout == null) {
        break missingId;
      }

      id = R.id.second;
      LinearLayout second = ViewBindings.findChildViewById(rootView, id);
      if (second == null) {
        break missingId;
      }

      id = R.id.third;
      LinearLayout third = ViewBindings.findChildViewById(rootView, id);
      if (third == null) {
        break missingId;
      }

      id = R.id.topleftoval;
      View topleftoval = ViewBindings.findChildViewById(rootView, id);
      if (topleftoval == null) {
        break missingId;
      }

      return new ActivityMainBinding((RelativeLayout) rootView, fifth, first, fourth, logout,
          panicBtn, relativeLayout, second, third, topleftoval);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
