// Generated by view binder compiler. Do not edit!
package com.project.sparkwomen.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.sparkwomen.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityLawsBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final Button backBtn;

  @NonNull
  public final ImageView imgLaw;

  @NonNull
  public final TextView layText;

  @NonNull
  public final RecyclerView recycleLaws;

  @NonNull
  public final View topleftoval;

  private ActivityLawsBinding(@NonNull RelativeLayout rootView, @NonNull Button backBtn,
      @NonNull ImageView imgLaw, @NonNull TextView layText, @NonNull RecyclerView recycleLaws,
      @NonNull View topleftoval) {
    this.rootView = rootView;
    this.backBtn = backBtn;
    this.imgLaw = imgLaw;
    this.layText = layText;
    this.recycleLaws = recycleLaws;
    this.topleftoval = topleftoval;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityLawsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityLawsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_laws, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityLawsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.backBtn;
      Button backBtn = ViewBindings.findChildViewById(rootView, id);
      if (backBtn == null) {
        break missingId;
      }

      id = R.id.imgLaw;
      ImageView imgLaw = ViewBindings.findChildViewById(rootView, id);
      if (imgLaw == null) {
        break missingId;
      }

      id = R.id.layText;
      TextView layText = ViewBindings.findChildViewById(rootView, id);
      if (layText == null) {
        break missingId;
      }

      id = R.id.recycleLaws;
      RecyclerView recycleLaws = ViewBindings.findChildViewById(rootView, id);
      if (recycleLaws == null) {
        break missingId;
      }

      id = R.id.topleftoval;
      View topleftoval = ViewBindings.findChildViewById(rootView, id);
      if (topleftoval == null) {
        break missingId;
      }

      return new ActivityLawsBinding((RelativeLayout) rootView, backBtn, imgLaw, layText,
          recycleLaws, topleftoval);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
