// Generated by view binder compiler. Do not edit!
package com.project.sparkwomen.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.project.sparkwomen.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySplashBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final Button btnGetStarted;

  @NonNull
  public final TextView slang;

  @NonNull
  public final ImageView sparkImg;

  @NonNull
  public final TextView sparkText;

  @NonNull
  public final View topleftoval;

  private ActivitySplashBinding(@NonNull RelativeLayout rootView, @NonNull Button btnGetStarted,
      @NonNull TextView slang, @NonNull ImageView sparkImg, @NonNull TextView sparkText,
      @NonNull View topleftoval) {
    this.rootView = rootView;
    this.btnGetStarted = btnGetStarted;
    this.slang = slang;
    this.sparkImg = sparkImg;
    this.sparkText = sparkText;
    this.topleftoval = topleftoval;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySplashBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySplashBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_splash, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySplashBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnGetStarted;
      Button btnGetStarted = ViewBindings.findChildViewById(rootView, id);
      if (btnGetStarted == null) {
        break missingId;
      }

      id = R.id.slang;
      TextView slang = ViewBindings.findChildViewById(rootView, id);
      if (slang == null) {
        break missingId;
      }

      id = R.id.sparkImg;
      ImageView sparkImg = ViewBindings.findChildViewById(rootView, id);
      if (sparkImg == null) {
        break missingId;
      }

      id = R.id.sparkText;
      TextView sparkText = ViewBindings.findChildViewById(rootView, id);
      if (sparkText == null) {
        break missingId;
      }

      id = R.id.topleftoval;
      View topleftoval = ViewBindings.findChildViewById(rootView, id);
      if (topleftoval == null) {
        break missingId;
      }

      return new ActivitySplashBinding((RelativeLayout) rootView, btnGetStarted, slang, sparkImg,
          sparkText, topleftoval);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
